# .github/workflows/embold-scan.yml

name: Embold Code Quality Scan

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  embold-scan:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Download and extract the Embold scanner
      - name: Download and Extract Scanner
        run: |
          curl https://v1.embold.io/nfs/CLI/browserstack-codequality-scanner.tar.gz -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      # Step 3: Download the repository configuration file using a secure Token 
      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET "http://18.184.13.138:3089/api/v1/repositories/a8123324c17be4014ab4177b0f5f4c6a/scans/config/download" --header "Authorization: Bearer ${{ secrets.EMBOLD_SCAN_TOKEN }}" -o repository-configuration.json

      # Step 4: Run the Embold analysis scanner
      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_SCAN_TOKEN }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u http://18.184.13.138:3089/ \
            -t $EMBOLD_TOKEN \
            -r a8123324c17be4014ab4177b0f5f4c6a \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home
